### ISSUE TITLE
Creating a new Experiment

### ISSUE THREAD

**Issue by jgross11** [jgross11/CS481-Project#14]
**User wants to create an experiment**
1. User navigates to home page
2. User logs into their profile
3. User navigates to Experiment page
4. User clicks “create experiment” button
5. User is directed to experiment page and a blank experiment is created
5a. User can select a preset template for an experiment type

**Comment by acastro7** [comment]
- Create experiment method gets built database side 0db79f033d7d18614cb2ab1aff27bf816abc8d49
-Create experiment gets worked on? by Josh 7976e5284f401a9a22de29a10a5b60e045bb8dbe
