### ISSUE TITLE
User access his profile information 

### ISSUE THREAD

**Issue by jstambaugh** [jgross11/CS481-Project#4]
1. User goes to their profile to view their profile information
2. System queries the database for profile information
3. Database searches the user table for profile information
4. Database returns any queried information in the database
5. System takes that information and displays it to User
6. User is hopefully happy with all the work System does for them

--Details 
We need to setup the database queries that will actually pull the data from the database to the page that requests the data.

**Comment by acastro7** [comment]
The method that does this database side should return a User Model Class

**Comment by jstambaugh** [comment]
Finished creating queries and functions for the User to access their profile information.
50ce1e058e2d5031722ef776b6dae0a11bcec8c8
69b386ab6a503df3015734f206a76c946321a35a
f0f070c6deb5e86c529bc2b402affbf2bd52ffef
