### ISSUE TITLE
Users need the ability to login

### ISSUE THREAD

**Issue by Dchism98** [jgross11/CS481-Project#8]
1. User navigates to home page
2. User hovers over login / signup / recover information button
3. User clicks “log in”
4. User supplies email and password
5. User supplied information is processed by backend
6. If verification is successful, user is redirected to home page as a user
6a. If verification is unsuccessful, user is directed to home page as guest and asked to try again.

**Comment by jgross11** [comment]
**User wants to sign up**
-User navigates to home page
-User hovers over login / signup / recover information button
-If user wants to sign up,
    User clicks “sign up”
    User is sent to sign up page
    User supplies information, including first and last name, email, password, school, and 1-3 security questions (from a list) and answers
    User is emailed a confirmation email requesting they click a generated link to confirm account creation intent
    User is directed to login page after information is verified
If user wants to log in, 
    User clicks “log in”
    User supplies email and password
    User supplied information is processed by backend
    If verification is successful, user is redirected to home page as a user
    If verification is unsuccessful, user is directed to home page as guest and asked to try again.
If user wants to obtain their information that they forgot, 
    User clicks “forgot information”
    User is directed to info recovery page
    If the user forgot their password, they are asked to input their email
        If their email is associated with an account, an email is generated containing a link to update their password
        If their email is not associated with an account, they are notified that their email doesn’t belong to an account and provided a link to the signup page.
    If the user forgot their email address, they are asked to input their first and last name
        If their first and last name is associated with an account, they are shown a subset of their security questions
            If the security questions are answered correctly, the email address associated with the account is shown
            If the security questions are not answered correctly, they are notified and given a different subset of security questions to answer
        If their first and last name is not associated with an account, they are notified that their first and last name is not associated with an account and provided a link to the signup page.

**Comment by acastro7** [comment]
Code for the user to login
-main code e2cd5e770f5e9a6b6443b8a05766794f65f1f996
-single edit of code pull be2ad2426edea21d45358487bd1bcaed3928e7d3
The test code on how to use VerifyUser(email String, userPassword String) f0f070c6deb5e86c529bc2b402affbf2bd52ffef

**Comment by jstambaugh** [comment]
Finished code for Login. Have VerifyUser Class done to check that use is in the database. 
706b499fff4784e604ebf353d3a47f82cf42010c
f0f070c6deb5e86c529bc2b402affbf2bd52ffef
